services:
  gateway:
    image: thevo/lafia-openmrs-gateway:dev
    platform: linux/amd64
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/nginx/gateway.conf:/etc/nginx/conf.d/default.conf
      - ./config/ssl:/etc/nginx/ssl:ro
    depends_on:
      - frontend
      - backend

  frontend:
    image: thevo/lafia-openmrs-frontend:alpha-dev
    platform: linux/amd64
    environment:
      - SPA_PATH=/openmrs/spa
      - API_URL=/openmrs
      - PUBLIC_URL=/openmrs/spa
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80/ || exit 0"]
      interval: 30s
      timeout: 10s
      retries: 3

  backend:
    image: 571600871041.dkr.ecr.eu-west-2.amazonaws.com/lafiaopenmrs-core-backend:latest
    platform: linux/amd64
    environment:
      - OMRS_CONFIG_MODULE_WEB_ADMIN=true
      - OMRS_CONFIG_AUTO_UPDATE_DATABASE=true
      - OMRS_CONFIG_CREATE_TABLES=true
      - OMRS_CONFIG_CONNECTION_SERVER=${HMS_DEV_DB_HOST}
      - OMRS_CONFIG_CONNECTION_DATABASE=${HMS_DEV_DB_NAME}
      - OMRS_CONFIG_CONNECTION_USERNAME=${HMS_DEV_DB_USER}
      - OMRS_CONFIG_CONNECTION_PASSWORD=${HMS_DEV_DB_PASSWORD}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/openmrs || exit 0"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    volumes:
      - openmrs-data:/openmrs/data

volumes:
  openmrs-data: ~