services:
  gateway:
      image: thevo/lafia-openmrs-gateway:dev
      platform: linux/amd64
      restart: unless-stopped
      depends_on:
        frontend:
          condition: service_healthy
        backend:
          condition: service_started
      ports:
        - "80:80"
        - "443:443"
      environment:
        - NGINX_ENVSUBST_TEMPLATE_SUFFIX=.template
        - NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx/conf.d
      volumes:
        - ./config/nginx/templates:/etc/nginx/templates
        - ./config/ssl:/etc/nginx/ssl:ro
      healthcheck:
        test: ["CMD", "nginx", "-t"]
        interval: 30s
        timeout: 10s
        retries: 3
        start_period: 40s
      networks:
        - openmrs-network
        - backend

  frontend:
    image: thevo/lafia-openmrs-frontend:dev
    platform: linux/amd64
    environment:
      - SPA_PATH=/openmrs/spa
      - API_URL=/openmrs

  backend:
    image: ${ECR_REPOSITORY}/lafiaopenmrs-core-backend:latest
    platform: linux/amd64
    environment:
      - OMRS_CONFIG_CONNECTION_SERVER=${HMS_DEV_DB_HOST}
      - OMRS_CONFIG_CONNECTION_DATABASE=${HMS_DEV_DB_NAME}
      - OMRS_CONFIG_CONNECTION_USERNAME=${HMS_DEV_DB_USER}
      - OMRS_CONFIG_CONNECTION_PASSWORD=${HMS_DEV_DB_PASSWORD}